"""
agent/reviewer_agent.py - Code Reviewer Agent

Acts as a Senior Staff Engineer to review git diffs generated by the SuperAgent.
"""

import os
import json
import logging
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv(override=True)
logger = logging.getLogger(__name__)

from config import get_config
from utils.retry import retry_network

config = get_config()

MODEL = config.model_id
API_BASE = config.openai_base_url
API_KEY = config.openai_api_key

client = OpenAI(
    api_key=API_KEY,
    base_url=API_BASE,
    timeout=60.0,
    max_retries=0
)

# 封装 API 调用
@retry_network(max_attempts=3, base_delay=2.0)
def _call_openai_with_retry(model: str, messages: list, temperature: float = 0.1, response_format=None):
    return client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
        response_format=response_format
    )

def review_code(task_description: str, git_diff: str, previous_critiques: list = None) -> dict:
    """
    Review the code changes and return a decision and critique.
    Returns: {"decision": "APPROVE" | "REJECT", "critique": "..."}
    """
    system_prompt = """You are an elite Senior Staff Software Engineer acting as a strict Code Reviewer.
Your job is to review the `git diff` generated by an AI coding agent for a specific task.

EVALUATION CRITERIA:
1. Correctness: Does the diff actually solve the user's request?
2. Safety & Edge Cases: Are there obvious bugs, logic flaws, or unhandled errors?
3. Leftover Debug Code: Did the agent leave behind `print()` statements or temporary assertions that shouldn't be in production?

OUTPUT FORMAT:
You MUST respond EXACTLY in the following JSON format without markdown wrapping (just raw JSON):
{
    "decision": "APPROVE", // or "REJECT"
    "critique": "If rejected, provide specific, actionable feedback on what the agent needs to fix. If approved, write a brief 'LGTM' style comment."
}"""

    user_prompt = f"### TASK DESCRIPTION\n{task_description}\n\n### GIT DIFF\n```diff\n{git_diff}\n```"

    if previous_critiques:
        history_text = "\n\n".join([f"Round {i+1} Rejection Reason:\n{c}" for i, c in enumerate(previous_critiques)])
        user_prompt += f"\n\n### PREVIOUS REVIEW HISTORY (DO NOT CONTRADICT YOUR PREVIOUS REQUESTS):\n{history_text}"

    try:
        # 🌟 使用重试装饰器自动处理网络错误
        response = _call_openai_with_retry(
            model=MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.1,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content.strip()
        
        # 兼容部分模型可能会返回 ```json ... ``` 的情况
        if content.startswith("```json"):
            content = content.replace("```json", "", 1)
            content = content.rsplit("```", 1)[0].strip()
            
        result = json.loads(content)
        
        # 兜底校验
        if result.get("decision") not in ["APPROVE", "REJECT"]:
            result["decision"] = "REJECT"
            result["critique"] = "Invalid decision format from reviewer."
            
        return result
        
    except Exception as e:
        logger.error(f"Reviewer Agent API Error: {e}")
        # 如果 Reviewer API 挂了，降级为 APPROVE 并附带警告，防止整个工作流卡死
        return {"decision": "APPROVE", "critique": f"⚠️ Reviewer API 异常，自动放行。Error: {str(e)}"}